name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs-antora:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build site with Antora
        uses: addnab/docker-run-action@v3
        with:
          image: antora/antora:2.3.1
          options: -v ${{ github.workspace }}:/antora:Z
          run: antora antora-playbook.yml --cache-dir=/tmp/.antora-cache

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
